name: Minimal tests for docker images

on:
  push:
    branches: [ main, dev, docker ]
  pull_request:
    branches: [ main, dev, docker ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - 
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - 
      name: Build Dockerfile
      timeout-minutes: 20
      run: |
            docker build -t fdu_testing -f ./docker/Dockerfile .

    - 
      name: Test Docker container
      timeout-minutes: 3
      run: |
          docker run --rm fdu_testing --help

    - 
      name: Install and Run Dive
      timeout-minutes: 2
      run: |
            pushd /tmp
            wget --no-verbose https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
            sudo apt install --quiet -y ./dive_0.9.2_linux_amd64.deb
            popd
            CI=true dive --ci-config "${{ github.workspace }}/.dive-ci" fdu_testing

    - 
      name: Build Dockerfile (PyInstaller)
      timeout-minutes: 10
      run: |
            docker build -t fdu_testing:pyinstaller -f ./docker/Dockerfile.pyinstaller .

    - 
      name: Test Docker container (PyInstaller)
      timeout-minutes: 3
      run: |
          docker run --rm fdu_testing:pyinstaller --help

    - 
      name: Run Dive
      timeout-minutes: 2
      run: |
            CI=true dive --ci-config "${{ github.workspace }}/.dive-ci" fdu_testing:pyinstaller
        